// src/services/spotify.service.js

import axios from "axios";
import { config } from "../config/env.js";
import { spotifyConfig } from "../config/spotify.js";
import { Queries } from "../db/queries.js";
import { getSpotifyTokens, updateAccessToken } from "./token.service.js";

const TOKEN_URL = spotifyConfig.tokenUrl;
const SPOTIFY_API = "https://api.spotify.com/v1";

const authHeader = () =>
  Buffer.from(
    `${config.SPOTIFY_CLIENT_ID}:${config.SPOTIFY_CLIENT_SECRET}`
  ).toString("base64");

//
// Exchange OAuth code for tokens
//
export const exchangeCodeForTokens = async (code) => {
  const params = new URLSearchParams();
  params.append("grant_type", "authorization_code");
  params.append("code", code);
  params.append("redirect_uri", config.SPOTIFY_REDIRECT_URI);

  const res = await axios.post(TOKEN_URL, params, {
    headers: {
      Authorization: `Basic ${authHeader()}`,
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });

  return {
    access_token: res.data.access_token,
    refresh_token: res.data.refresh_token,
    expires_at: Date.now() + res.data.expires_in * 1000
  };
};

//
// Refresh access token only if expired (or within 60s of expiry).
// Saves a Spotify API round-trip on every request when the token is still valid.
//
const EXPIRY_BUFFER_MS = 60 * 1000;

export const refreshAccessToken = async (userId) => {
  const tokens = await getSpotifyTokens(userId);

  const isExpired = !tokens.expires_at || Date.now() >= tokens.expires_at - EXPIRY_BUFFER_MS;

  if (!isExpired) {
    return tokens.access_token;
  }

  const params = new URLSearchParams();
  params.append("grant_type", "refresh_token");
  params.append("refresh_token", tokens.refresh_token);

  const res = await axios.post(TOKEN_URL, params, {
    headers: {
      Authorization: `Basic ${authHeader()}`,
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });

  const newAccess = res.data.access_token;
  const newExpiresAt = Date.now() + res.data.expires_in * 1000;

  await updateAccessToken(userId, newAccess, newExpiresAt);

  return newAccess;
};

//
// Create playlist + add tracks
//
export const createSpotifyPlaylist = async (userId, name, tracks) => {
  const accessToken = await refreshAccessToken(userId);

  // Create playlist using /me/playlists instead of /users/{id}/playlists
  const playlist = await axios.post(
    `${SPOTIFY_API}/me/playlists`,
    {
      name,
      description: "Generated by Dad DJ",
      public: true
    },
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  const playlistId = playlist.data.id;

  // Add tracks
  const uris = tracks.map((t) => t.uri);
  await axios.post(
    `${SPOTIFY_API}/playlists/${playlistId}/tracks`,
    { uris },
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  // Save playlist history
  await Queries.savePlaylistHistory(userId, {
    spotify_playlist_id: playlistId,
    name,
    segments_used: tracks
  });

  return {
    playlist_id: playlistId,
    url: playlist.data.external_urls.spotify
  };
};