// src/services/spotify.service.js

import axios from "axios";
import { config } from "../config/env.js";
import { spotifyConfig } from "../config/spotify.js";
import { Queries } from "../db/queries.js";

const TOKEN_URL = spotifyConfig.tokenUrl;
const SPOTIFY_API = "https://api.spotify.com/v1";

const authHeader = () =>
  Buffer.from(
    `${config.SPOTIFY_CLIENT_ID}:${config.SPOTIFY_CLIENT_SECRET}`
  ).toString("base64");

//
// Exchange OAuth code for tokens
//
export const exchangeCodeForTokens = async (code) => {
  const params = new URLSearchParams();
  params.append("grant_type", "authorization_code");
  params.append("code", code);
  params.append("redirect_uri", config.SPOTIFY_REDIRECT_URI);

  const res = await axios.post(TOKEN_URL, params, {
    headers: {
      Authorization: `Basic ${authHeader()}`,
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });

  return {
    access_token: res.data.access_token,
    refresh_token: res.data.refresh_token,
    expires_at: Date.now() + res.data.expires_in * 1000
  };
};

//
// Refresh access token
//
export const refreshAccessToken = async (userId) => {
  const tokens = await Queries.getSpotifyTokens(userId);

  const params = new URLSearchParams();
  params.append("grant_type", "refresh_token");
  params.append("refresh_token", tokens.refresh_token);

  const res = await axios.post(TOKEN_URL, params, {
    headers: {
      Authorization: `Basic ${authHeader()}`,
      "Content-Type": "application/x-www-form-urlencoded"
    }
  });

  const newAccess = res.data.access_token;

  await Queries.updateAccessToken(userId, newAccess);

  return newAccess;
};

//
// Create playlist + add tracks
//
export const createSpotifyPlaylist = async (userId, name, tracks) => {
  const accessToken = await refreshAccessToken(userId);

  // 1. Get Spotify user ID
  const me = await axios.get(`${SPOTIFY_API}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  });

  const spotifyUserId = me.data.id;

  // 2. Create playlist
  const playlist = await axios.post(
    `${SPOTIFY_API}/users/${spotifyUserId}/playlists`,
    {
      name,
      description: "Generated by Dad DJ",
      public: false
    },
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  const playlistId = playlist.data.id;

  // 3. Add tracks
  const uris = tracks.map((t) => t.uri);

  await axios.post(
    `${SPOTIFY_API}/playlists/${playlistId}/tracks`,
    { uris },
    { headers: { Authorization: `Bearer ${accessToken}` } }
  );

  // 4. Save playlist history
  await Queries.savePlaylistHistory(userId, {
    spotify_playlist_id: playlistId,
    name,
    segments_used: tracks
  });

  return {
    playlist_id: playlistId,
    url: playlist.data.external_urls.spotify
  };
};